//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagasinEnLigne.MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public System.Guid id { get; set; }
        public string nom { get; set; }
        public string description { get; set; }
        public Nullable<int> quantite { get; set; }
        public Nullable<int> prixUnit { get; set; }
        public byte[] photo { get; set; }
    }
}
