//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EssaiExam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebEssaiExamEntities : DbContext
    {
        public WebEssaiExamEntities()
            : base("name=WebEssaiExamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetCategories_Result> GetCategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCategories_Result>("GetCategories");
        }
    
        public virtual ObjectResult<GetDistinctLocalite_Result> GetDistinctLocalite()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDistinctLocalite_Result>("GetDistinctLocalite");
        }
    
        public virtual ObjectResult<GetBuildingsByLocationANDnumbersOfRoomsANDTypeOfBuilding_Result> GetBuildingsByLocationANDnumbersOfRoomsANDTypeOfBuilding(Nullable<System.Guid> locationID, Nullable<int> minNumberOfRooms, Nullable<int> maxNumberOfRooms, Nullable<System.Guid> typeOfBuilding)
        {
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("locationID", locationID) :
                new ObjectParameter("locationID", typeof(System.Guid));
    
            var minNumberOfRoomsParameter = minNumberOfRooms.HasValue ?
                new ObjectParameter("minNumberOfRooms", minNumberOfRooms) :
                new ObjectParameter("minNumberOfRooms", typeof(int));
    
            var maxNumberOfRoomsParameter = maxNumberOfRooms.HasValue ?
                new ObjectParameter("maxNumberOfRooms", maxNumberOfRooms) :
                new ObjectParameter("maxNumberOfRooms", typeof(int));
    
            var typeOfBuildingParameter = typeOfBuilding.HasValue ?
                new ObjectParameter("typeOfBuilding", typeOfBuilding) :
                new ObjectParameter("typeOfBuilding", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBuildingsByLocationANDnumbersOfRoomsANDTypeOfBuilding_Result>("GetBuildingsByLocationANDnumbersOfRoomsANDTypeOfBuilding", locationIDParameter, minNumberOfRoomsParameter, maxNumberOfRoomsParameter, typeOfBuildingParameter);
        }
    
        public virtual ObjectResult<string> GetDescriptionFromId(Nullable<System.Guid> idBien)
        {
            var idBienParameter = idBien.HasValue ?
                new ObjectParameter("idBien", idBien) :
                new ObjectParameter("idBien", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetDescriptionFromId", idBienParameter);
        }
    }
}
