//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caching.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendeur
    {
        public int id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
    }
}
