<?xml version="1.0" encoding="utf-8"?><Database Name="TestDatabase" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=TestDatabase;Persist Security Info=True;User ID=User" SettingsObjectName="SQL__16_03_18_.Properties.Settings" SettingsPropertyName="TestDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Clients">
      <Column Name="idClient" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="prenom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ville" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="telephone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>