//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientsList.MVVM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Info2020Entities : DbContext
    {
        public Info2020Entities()
            : base("name=Info2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetXAMLClients_Result> GetXAMLClients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetXAMLClients_Result>("GetXAMLClients");
        }
    
        public virtual ObjectResult<GetNameXAMLClients_Result> GetNameXAMLClients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNameXAMLClients_Result>("GetNameXAMLClients");
        }
    
        public virtual ObjectResult<GetXAMLClientByInfo_Result> GetXAMLClientByInfo(Nullable<System.Guid> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetXAMLClientByInfo_Result>("GetXAMLClientByInfo", clientIDParameter);
        }
    }
}
