//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framework_Model_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        public int idVehicule { get; set; }
        public short cylindree { get; set; }
        public string marque { get; set; }
    }
}
